## Lesson 1 Exercise 1: Creating a Table with PostgreSQL

In [1]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.6.tar.gz (383 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.0/384.0 kB 10.0 MB/s eta 0:00:0000:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.6-cp310-cp310-linux_x86_64.whl size=166815 sha256=461ac35dbd5309f33bb0bdd3ce7fc4f8d94cac4e36571d24d4d9fe9725524657
  Stored in directory: /root/.cache/pip/wheels/a2/65/83/78e6f42d3b8e22115e894576b71799d96ab5a790b8f7bcfa85
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.6

## Import the library

In [2]:
import psycopg2

## Create a connection to the database

In [8]:
try:
    conn = psycopg2.connect("host='localhost' port=5433 dbname=postgres user=postgres password=Zorro123")
    print("Connection to the PostgreSQL database successful.")
    # You can perform further operations with the connection here if needed.
    # For example, executing SQL queries or accessing data from the database.
    # Don't forget to close the connection when you are done.
    # conn.close()
except psycopg2.Error as e:
    print("Error: Could not make a connection to the Postgres database")
    print(e)

Error: Could not make a connection to the Postgres database
connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

## Use the connection to get a cursor that can be used to execute queries.

In [4]:
try: 
    cur = conn.cursor()
except psycopg2.Error as e: 
    print("Error: Could not get curser to the Database")
    print(e)

## Set automatic commit to be true so that each action is committed without having to call conn.commit() after each command.

In [5]:
conn.set_session(autocommit=True)

## Create a database to do the work in

In [6]:
try: 
    cur.execute("create database myfirstdb")
except psycopg2.Error as e:
    print(e)

database "myfirstdb" already exists

## Add the database name in the connect statement. Let's close our connection to the default database, reconnect to the Udacity database, and get a new cursor.

In [7]:
try: 
    conn.close()
except psycopg2.Error as e:
    print(e)
    
try: 
    conn = psycopg2.connect("host=127.0.0.1 dbname=myfirstdb user=postgres password=root")
except psycopg2.Error as e: 
    print("Error: Could not make connection to the Postgres database")
    print(e)
    
try: 
    cur = conn.cursor()
except psycopg2.Error as e: 
    print("Error: Could not get curser to the Database")
    print(e)

conn.set_session(autocommit=True)

## Create Table for students which includes below columns

student_id <br>
name <br>
age <br>
gender <br>
subject <br>
marks

In [8]:
try: 
    cur.execute("CREATE TABLE IF NOT EXISTS students (student_id int, name varchar,\
    age int, gender varchar, subject varchar, marks int);")
except psycopg2.Error as e: 
    print("Error: Issue creating table")
    print (e)

### Insert the following two rows in the table
First Row:  1, "Raj", 23, "Male", "Python", 85

Second Row: 2, "Priya", 22, "Female", "Python", 86

In [9]:
try: 
    cur.execute("INSERT INTO students (student_id, name, age, gender, subject, marks) \
                 VALUES (%s, %s, %s, %s, %s, %s)", \
                 (1, "Raj", 23, "Male", "Python", 85))
except psycopg2.Error as e: 
    print("Error: Inserting Rows")
    print (e)
    
try: 
    cur.execute("INSERT INTO students (student_id, name, age, gender, subject, marks) \
                  VALUES (%s, %s, %s, %s, %s, %s)",
                  ( 2, "Priya", 22, "Female", "Python", 86))
except psycopg2.Error as e: 
    print("Error: Inserting Rows")
    print (e)

## Validate your data was inserted into the table.

In [10]:
try: 
    cur.execute("SELECT * FROM students;")
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone()

(1, 'Raj', 23, 'Male', 'Python', 85)

(2, 'Priya', 22, 'Female', 'Python', 86)

##  And finally close your cursor and connection.

In [11]:
cur.close()
conn.close()